#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

PADDING=60 
PADDLEFT=30
bspc config left_padding $PADDLEFT
bspc config right_padding $PADDLEFT
bspc config bottom_padding $PADDING
bspc config top_padding 30
bspc config split_ratio 0.50
bspc config swallow_first_click false
bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#87CEEB"
#bspc config normal_border_color "#FFFFFF"
#bspc config focused_border_color "#FF0000"

# 设置为浮动窗口
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a google-chrome-bate desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on 
bspc rule -a Screenkey manage=on
bspc rule -a vlc state=floating
